/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_clipboardagent_DispatchHelper */

#ifndef _Included_com_intel_clipboardagent_DispatchHelper
#define _Included_com_intel_clipboardagent_DispatchHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_clipboardagent_DispatchHelper
 * Method:    registerComponent
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_clipboardagent_DispatchHelper_registerComponent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_intel_clipboardagent_DispatchHelper
 * Method:    sendMsg
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_intel_clipboardagent_DispatchHelper_sendMsg
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_intel_clipboardagent_DispatchHelper
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_clipboardagent_DispatchHelper_start
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_clipboardagent_DispatchHelper
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_clipboardagent_DispatchHelper_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
